#!/bin/bash
#install go lang
#install tools
	#findomain
	#assetfinder
	#subfinder
	
	
# Update and upgrade the system
sudo apt update 


mkdir /home/0xSkipper/Desktop/Recon/
mkdir /home/0xSkipper/Desktop/Recon/tools


# Install dependencies
sudo apt install -y git wget golang-go python3-pip

#####install findomain ##########

echo "install findomain start "
cd /home/0xSkipper/Desktop/Recon/tools
git clone https://github.com/findomain/findomain.git
cd findomain
apt install cargo -y
cargo build --release -y
sudo cp target/release/findomain /usr/bin/
findomain
echo "install findomain end"



#######assetfinder##############

echo "Install assetfinder start"
sudo apt install assetfinder -y 
echo "Install assetfinder end"


#######subfinder#######
echo "Install subfinder start"
go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
~/go/bin/subfinder -h
sudo ln -s ~/go/bin/subfinder /usr/local/bin/subfinder
echo "Install subfinder end"

